from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, status
from pydantic import BaseModel

from app.auth.router import get_current_user
from app.analysis.service import validate_file, analyze_ct_image

router = APIRouter(prefix="/api", tags=["analysis"])


class AnalysisResponse(BaseModel):
    filename: str
    analysis: str
    disclaimer: str


DISCLAIMER = (
    "This analysis was generated by an AI system for educational/research purposes only. "
    "It is NOT a medical diagnosis and should NOT be used as the basis for any medical decisions. "
    "Always consult qualified medical professionals."
)


@router.post("/analyze", response_model=AnalysisResponse)
async def analyze_image(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    file_content = await file.read()
    file_size = len(file_content)

    is_valid, error_message = validate_file(file.filename, file_size, file_content)
    if not is_valid:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=error_message)

    try:
        analysis = analyze_ct_image(file_content, file.filename)
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Analysis failed: {str(e)}",
        )

    return AnalysisResponse(
        filename=file.filename,
        analysis=analysis,
        disclaimer=DISCLAIMER,
    )
