import base64
from io import BytesIO
from pathlib import Path

import anthropic
from PIL import Image

from app.config import ANTHROPIC_API_KEY, SUPPORTED_EXTENSIONS, MAX_FILE_SIZE

CT_ANALYSIS_PROMPT = """You are analyzing a CT (Computed Tomography) scan image. Please provide a detailed analysis including:

1. **Image Quality Assessment**: Comment on the image quality, visibility, and any artifacts.

2. **Anatomical Observations**: Describe the visible anatomical structures and their appearance.

3. **Notable Findings**: Identify any abnormalities, lesions, or areas of concern that are visible.

4. **Technical Details**: If identifiable, note the scan type, orientation, and contrast usage.

5. **Summary**: Provide a brief summary of your observations.

IMPORTANT DISCLAIMER: This analysis is generated by an AI for educational/research purposes only.
It is NOT a medical diagnosis and should NOT be used as the basis for any medical decisions.
Always consult qualified radiologists and medical professionals for proper interpretation of medical images."""

MEDIA_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
}


def get_media_type(filename: str) -> str:
    ext = Path(filename).suffix.lower()
    return MEDIA_TYPES.get(ext, "image/jpeg")


def validate_file(filename: str, file_size: int, file_content: bytes) -> tuple[bool, str]:
    ext = Path(filename).suffix.lower()
    if ext not in SUPPORTED_EXTENSIONS:
        return False, f"Unsupported file type. Allowed: {', '.join(SUPPORTED_EXTENSIONS)}"

    if file_size > MAX_FILE_SIZE:
        return False, f"File too large. Maximum size: {MAX_FILE_SIZE // (1024*1024)} MB"

    try:
        img = Image.open(BytesIO(file_content))
        img.verify()
    except Exception:
        return False, "Invalid image file"

    return True, ""


def analyze_ct_image(file_content: bytes, filename: str) -> str:
    if not ANTHROPIC_API_KEY:
        raise ValueError("ANTHROPIC_API_KEY not configured")

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    image_data = base64.standard_b64encode(file_content).decode("utf-8")
    media_type = get_media_type(filename)

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2048,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": image_data,
                        },
                    },
                    {
                        "type": "text",
                        "text": CT_ANALYSIS_PROMPT,
                    },
                ],
            }
        ],
    )

    return message.content[0].text
