#!/usr/bin/env python3
"""
AI CT Observer - Watches a directory for CT images and analyzes them using Claude Vision API.

DISCLAIMER: This tool is for educational/research purposes only. It should NOT be used
for actual medical diagnosis. Always consult qualified medical professionals.
"""

import base64
import os
import sys
import time
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import anthropic
from PIL import Image

# Load environment variables
load_dotenv()

# Configuration
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
WATCH_PATH = os.getenv("WATCH_PATH", "./ct_images")
SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}

# Analysis prompt for CT images
CT_ANALYSIS_PROMPT = """You are analyzing a CT (Computed Tomography) scan image. Please provide a detailed analysis including:

1. **Image Quality Assessment**: Comment on the image quality, visibility, and any artifacts.

2. **Anatomical Observations**: Describe the visible anatomical structures and their appearance.

3. **Notable Findings**: Identify any abnormalities, lesions, or areas of concern that are visible.

4. **Technical Details**: If identifiable, note the scan type, orientation, and contrast usage.

5. **Summary**: Provide a brief summary of your observations.

IMPORTANT DISCLAIMER: This analysis is generated by an AI for educational/research purposes only.
It is NOT a medical diagnosis and should NOT be used as the basis for any medical decisions.
Always consult qualified radiologists and medical professionals for proper interpretation of medical images."""


def get_media_type(file_path: Path) -> str:
    """Get the media type for the image based on file extension."""
    extension = file_path.suffix.lower()
    media_types = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp",
    }
    return media_types.get(extension, "image/jpeg")


def encode_image_to_base64(file_path: Path) -> str:
    """Read an image file and encode it to base64."""
    with open(file_path, "rb") as image_file:
        return base64.standard_b64encode(image_file.read()).decode("utf-8")


def analyze_image(client: anthropic.Anthropic, image_path: Path) -> str:
    """Send image to Claude Vision API for analysis."""
    print(f"  Encoding image...")
    image_data = encode_image_to_base64(image_path)
    media_type = get_media_type(image_path)

    print(f"  Sending to Claude Vision API...")
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2048,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": image_data,
                        },
                    },
                    {
                        "type": "text",
                        "text": CT_ANALYSIS_PROMPT,
                    },
                ],
            }
        ],
    )

    return message.content[0].text


def write_analysis_result(image_path: Path, analysis: str) -> Path:
    """Write analysis result to a text file."""
    output_filename = f"{image_path.stem}_analysis.txt"
    output_path = image_path.parent / output_filename

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""CT Image Analysis Report
{'=' * 50}
Source Image: {image_path.name}
Analysis Date: {timestamp}
{'=' * 50}

{analysis}

{'=' * 50}
DISCLAIMER: This analysis was generated by an AI system for educational/research
purposes only. It is NOT a medical diagnosis and should NOT be used as the basis
for any medical decisions. Always consult qualified medical professionals.
{'=' * 50}
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path


class CTImageHandler(FileSystemEventHandler):
    """Handler for new CT image files."""

    def __init__(self, client: anthropic.Anthropic):
        self.client = client
        self.processed_files = set()

    def on_created(self, event):
        """Handle new file creation events."""
        if event.is_directory:
            return

        file_path = Path(event.src_path)

        # Check if file has supported extension
        if file_path.suffix.lower() not in SUPPORTED_EXTENSIONS:
            return

        # Avoid processing the same file multiple times
        if str(file_path) in self.processed_files:
            return

        self.processed_files.add(str(file_path))

        # Wait briefly for file to be fully written
        time.sleep(0.5)

        self.process_image(file_path)

    def process_image(self, file_path: Path):
        """Process a single CT image."""
        print(f"\n[NEW IMAGE] Detected: {file_path.name}")

        try:
            # Verify the file is a valid image
            print(f"  Validating image...")
            with Image.open(file_path) as img:
                print(f"  Image size: {img.size[0]}x{img.size[1]}, Format: {img.format}")

            # Analyze with Claude Vision
            print(f"  Analyzing with Claude Vision API...")
            analysis = analyze_image(self.client, file_path)

            # Write results
            output_path = write_analysis_result(file_path, analysis)
            print(f"  Analysis complete! Results saved to: {output_path.name}")

        except Exception as e:
            print(f"  Error processing {file_path.name}: {e}")


def main():
    """Main entry point."""
    print("=" * 60)
    print("AI CT Observer")
    print("=" * 60)
    print()
    print("DISCLAIMER: This tool is for educational/research purposes only.")
    print("It should NOT be used for actual medical diagnosis.")
    print()

    # Validate API key
    if not ANTHROPIC_API_KEY:
        print("ERROR: ANTHROPIC_API_KEY not set.")
        print("Please set it in your environment or create a .env file.")
        print("See .env.example for reference.")
        sys.exit(1)

    # Create watch directory if it doesn't exist
    watch_path = Path(WATCH_PATH)
    watch_path.mkdir(parents=True, exist_ok=True)

    print(f"Watching directory: {watch_path.absolute()}")
    print(f"Supported formats: {', '.join(SUPPORTED_EXTENSIONS)}")
    print()
    print("Drop CT images into the watched directory to analyze them.")
    print("Press Ctrl+C to stop.")
    print("-" * 60)

    # Initialize Claude client
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    # Set up file watcher
    event_handler = CTImageHandler(client)
    observer = Observer()
    observer.schedule(event_handler, str(watch_path), recursive=False)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n\nShutting down...")
        observer.stop()

    observer.join()
    print("Goodbye!")


if __name__ == "__main__":
    main()
